spring.application.name=sb-ecommerce

spring.h2.console.enabled = true
spring.datasource.url = jdbc:h2:mem:test

project.image=images/


#spring.jpa.show-sql = true
#spring.jpa.properties.hibernate.format-sql = true
#spring.jpa.hibernate.ddl-auto = create / create-drop / update


spring.app.secretToken = springSecurity12390l0ijhtjhgfdsrthbvcddftyhgtfre4565
spring.app.expirationTimeMs = 3600000

spring.ecom.app.jwtCookieName = SpringBootEcom

logging.level.org.springframework = DEBUG
logging.level.org.hibernate.SQL = DEBUG
logging.level.org.springframework.security = DEBUG
logging.level.com.ecommerce.project = DEBUG